### Get Active Classrooms
GET http://localhost:3003/classroomsActives

### Get Students & Name Students
GET http://localhost:3003/students?name=lau

### Create Classroom
POST http://localhost:3003/classrooms
Content-Type: application/json

{
    "name": "Simpsons",
    "module": "0"
}

### Create Students
POST http://localhost:3003/students
Content-Type: application/json

{
    "name": "Thiago",
    "email": "thiago@gmail.com",
    "birthdate": "1984/07/01",
    "classroom_id": "01"
}

### Update Module Classroom
PUT http://localhost:3003/classrooms/03
Content-Type: application/json

{
    "module": "4"
}

### Update Classroom Student
PUT http://localhost:3003/students/23
Content-Type: application/json

{
    "classroom_id": "03"
}
